version: '3.5'

networks:
  broker-net:
    driver: bridge

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: 'bitnami/zookeeper:3'
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=no
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./data/zookeeper:/bitnami/zookeeper
      - ./logs/zookeeper:/opt/bitnami/zookeeper/logs
    networks:
      - broker-net

  kafka:
    container_name: kafka
    hostname: kafka
    image: 'bitnami/kafka:2'
    restart: unless-stopped
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - ./data/kafka:/bitnami/kafka
      - ./logs/kafka:/opt/bitnami/kafka/logs
    networks:
      - broker-net